<?php 

$GLOBALS['SITE'] = "SOPER";
$GLOBALS['site'] = $GLOBALS['SITE']; // HOLD OVER UNTIL WE FIND REMAINING LITTLE CASE 'site'
$GLOBALS[$SITE]['SYS_SLUG'] = "SOPER";
$GLOBALS[$SITE]['SYS_DISPLAY'] = "SOPER";
$GLOBALS[$SITE]['SYS'] = "SOPER";
$GLOBALS[$SITE]['URI'] = "SOPER";

// 