<?php 

$GLOBALS['SITE'] = "JUKEBOX";
$GLOBALS['site'] = $GLOBALS['SITE']; // HOLD OVER UNTIL WE FIND REMAINING LITTLE CASE 'site'
$GLOBALS[$SITE]['SYS_SLUG'] = "JUKEBOX";
$GLOBALS[$SITE]['SYS_DISPLAY'] = "THE JUKEBOX";
$GLOBALS[$SITE]['SYS'] = "JUKEBOX";
$GLOBALS[$SITE]['URI'] = "JUKEBOX";

// 