<?php 
$GLOBALS['sys'] = "SKYLINE";
$GLOBALS['dom'] = "PUBLIC_OFFICE";
$GLOBALS['mod'] = "CLERK";
$GLOBALS['site'] = "SKYLINE";
$GLOBALS['SITE_SLUG'] = "SKYLINE";


$GLOBALS['SITE'] = "SKYLINE";
$GLOBALS[$SITE]['SYS'] = "SKYLINE";
$GLOBALS[$SITE]['DOM'] = "PUBLIC_OFFICE";
$GLOBALS[$SITE]['MOD'] = "CLERK";
$GLOBALS[$SITE]['URI'] = "SKYLINE";

// 