<?php 
# $GLOBALS['sys'] = "SKYLINE";
# $GLOBALS['dom'] = "PUBLIC_OFFICE";
# $GLOBALS['mod'] = "CLERK";
 $GLOBALS['site'] = "SKYLINE";

$GLOBALS['SITE'] = "SKYLINE";
$GLOBALS[$SITE]['SYS_SLUG'] = "SKYLINE";
$GLOBALS[$SITE]['SYS_DISPLAY'] = "SKYLINE ON INTERA";
$GLOBALS[$SITE]['SYS'] = "SKYLINE";
$GLOBALS[$SITE]['URI'] = "SKYLINE";

// 