<?php 
# $GLOBALS['sys'] = "SKYLINE";
# $GLOBALS['dom'] = "PUBLIC_OFFICE";
# $GLOBALS['mod'] = "CLERK";

$GLOBALS['SITE'] = "SKYLINE";
$GLOBALS['site'] = $GLOBALS['SITE']; // HOLD OVER UNTIL WE FIND REMAINING LITTLE CASE 'site'
$GLOBALS[$SITE]['SYS_SLUG'] = "SKYLINE";
$GLOBALS[$SITE]['SYS_DISPLAY'] = "SKYLINE ON INTERA";
$GLOBALS[$SITE]['SYS'] = "SKYLINE";
$GLOBALS[$SITE]['URI'] = "SKYLINE";

// 