<?php 

$GLOBALS['SITE'] = "MYTHLEAK";
$GLOBALS['site'] = $GLOBALS['SITE']; // HOLD OVER UNTIL WE FIND REMAINING LITTLE CASE 'site'
$GLOBALS[$SITE]['SYS_SLUG'] = "MYTHLEAK";
$GLOBALS[$SITE]['SYS_DISPLAY'] = "MYTHLEAK: WE HAVE THE RECIEPTS";
$GLOBALS[$SITE]['SYS'] = "MYTHLEAK";
$GLOBALS[$SITE]['URI'] = "MYTHLEAK";

// 