<?php 

$GLOBALS['SITE'] = "{{WORLD_NAME}}";
$GLOBALS['site'] = $GLOBALS['SITE']; // HOLD OVER UNTIL WE FIND REMAINING LITTLE CASE 'site'
$GLOBALS[$SITE]['SYS_SLUG'] = "{{WORLD_NAME}}";
$GLOBALS[$SITE]['SYS_DISPLAY'] = "{{WORLD_NAME}}";
$GLOBALS[$SITE]['SYS'] = $GLOBALS[$SITE]['SYS_SLUG'];
$GLOBALS[$SITE]['URI'] = "{{URI}}";

// 

?>