<?php 

$GLOBALS['SITE'] = "TERMINAL";
$GLOBALS['site'] = $GLOBALS['SITE']; // HOLD OVER UNTIL WE FIND REMAINING LITTLE CASE 'site'
$GLOBALS[$SITE]['SYS_SLUG'] = "TERMINAL";
$GLOBALS[$SITE]['SYS_DISPLAY'] = "TERMINAL/ROOT";
$GLOBALS[$SITE]['SYS'] = $GLOBALS[$SITE]['SYS_SLUG'];
$GLOBALS[$SITE]['URI'] = "TERMINAL/IO";

// 